name: Check code

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Run with latest stable Deno.

      # Check if the code is formatted according to Deno's default
      # formatting conventions.
      - name: Check formatting
        run: deno fmt --check

      # Scan the code for syntax errors and style issues. If
      # you want to use a custom linter configuration you can add a configuration file with --config <myconfig>
      - name: Lint code
        run: deno lint

      # Run all test files in the repository and collect code coverage. The example
      # runs with all permissions, but it is recommended to run with the minimal permissions your program needs (for example --allow-read).
      - name: Run tests
        run: deno test --allow-all --coverage=cov/

        # This generates a report from the collected coverage in `deno test --coverage`. It is
        # stored as a .lcov file which integrates well with services such as Codecov, Coveralls and Travis CI.
      - name: Generate coverage report
        run: deno coverage --lcov cov/ > cov.lcov

      - name: Upload coverage to Coveralls.io
        uses: coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Generated by GitHub.
          file: cov.lcov
